# Generated by Django 2.1.1 on 2020-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('aadhar', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=40)),
                ('facebook', models.CharField(default='NA', max_length=150)),
                ('twitter', models.CharField(default='NA', max_length=150)),
                ('linkedin', models.CharField(default='NA', max_length=150)),
                ('status', models.CharField(max_length=10)),
                ('agentpic', models.ImageField(upload_to='agentpic')),
            ],
            options={
                'db_table': 'agent_account',
            },
        ),
        migrations.CreateModel(
            name='myaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to='pic')),
            ],
            options={
                'db_table': 'myaccount',
            },
        ),
        migrations.CreateModel(
            name='PropertyCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_ID', models.CharField(max_length=100)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Category_Image', models.ImageField(upload_to='categoryimages/')),
            ],
            options={
                'db_table': 'PropertyCategoryData',
            },
        ),
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_ID', models.CharField(max_length=100)),
                ('Property_Name', models.CharField(max_length=100)),
                ('Property_About', models.CharField(max_length=1000)),
                ('Property_Address', models.CharField(max_length=1000)),
                ('Property_Area', models.CharField(max_length=1000)),
                ('Property_Beds', models.CharField(max_length=50)),
                ('Property_Baths', models.CharField(max_length=50)),
                ('Property_Garages', models.CharField(max_length=50)),
                ('Property_Price', models.CharField(max_length=50)),
                ('Property_Category', models.CharField(max_length=100)),
                ('Property_BuiltYear', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PropertyData',
            },
        ),
        migrations.CreateModel(
            name='PropertyImagesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_ID', models.CharField(max_length=100)),
                ('Property_Image', models.ImageField(upload_to='propertyimages/')),
            ],
            options={
                'db_table': 'PropertyImagesData',
            },
        ),
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
