# Generated by Django 2.1.1 on 2020-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20)),
                ('blog_no', models.CharField(max_length=50)),
                ('pic_of_pro', models.ImageField(upload_to='blog_pic')),
                ('date', models.DateField(auto_now=True)),
                ('subject', models.CharField(max_length=60)),
                ('Desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
