# Generated by Django 2.1.1 on 2020-04-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0002_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blog_table',
        ),
        migrations.AlterModelTable(
            name='blog_table',
            table='blog_table',
        ),
    ]
