# Generated by Django 2.1.1 on 2020-06-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0003_auto_20200412_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_ID', models.CharField(max_length=100)),
                ('Order_ID', models.CharField(max_length=50)),
                ('User_Email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CartData',
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=100)),
                ('Order_Date', models.DateField(auto_now=True)),
                ('Property_ID', models.CharField(max_length=100)),
                ('Property_Name', models.CharField(max_length=100)),
                ('Buyer_ID', models.CharField(max_length=100)),
                ('Payment_ID', models.CharField(blank=True, max_length=100)),
                ('Order_Status', models.CharField(max_length=100)),
                ('Total_Amount', models.CharField(max_length=100)),
                ('Amount_to_Pay', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OrderData',
            },
        ),
    ]
