# Generated by Django 2.1.1 on 2020-06-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0004_cartdata_orderdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartData',
        ),
    ]
