# Generated by Django 2.1.1 on 2020-06-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0007_user_account_userpic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_account',
        ),
    ]
