# Generated by Django 2.1.1 on 2020-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0009_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='userpic',
            field=models.ImageField(blank=True, upload_to='userpic/'),
        ),
    ]
