# Generated by Django 2.1.1 on 2020-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0010_auto_20200603_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='Property_status',
            field=models.CharField(default='FOR SALE', max_length=50),
        ),
    ]
