# Generated by Django 2.1.1 on 2020-06-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0011_propertydata_property_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_account',
        ),
    ]
