# Generated by Django 2.1.1 on 2020-06-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0013_user_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyData',
        ),
    ]
