# Generated by Django 2.1.1 on 2020-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0014_delete_propertydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_ID', models.CharField(max_length=100)),
                ('Property_Name', models.CharField(max_length=100)),
                ('Property_About', models.CharField(max_length=1000)),
                ('Property_Address', models.CharField(max_length=1000)),
                ('Property_Area', models.CharField(max_length=1000)),
                ('Property_Beds', models.CharField(max_length=50)),
                ('Property_Baths', models.CharField(max_length=50)),
                ('Property_Garages', models.CharField(max_length=50)),
                ('Property_Price', models.CharField(max_length=50)),
                ('Property_Category', models.CharField(max_length=100)),
                ('Property_BuiltYear', models.CharField(max_length=50)),
                ('Property_status', models.CharField(default='FOR SALE', max_length=50)),
                ('Property_location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PropertyData',
            },
        ),
    ]
