# Generated by Django 2.1.1 on 2020-06-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0015_propertydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_table',
        ),
    ]
