# Generated by Django 2.1.1 on 2020-06-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0017_blog_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyData',
        ),
    ]
