# Generated by Django 2.1.1 on 2020-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0019_propertydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapapproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_ID', models.CharField(max_length=100)),
                ('Buyer_ID', models.CharField(max_length=100)),
                ('Land_Paper', models.ImageField(upload_to='map_approval')),
                ('Map_by_engineer', models.ImageField(upload_to='map_by_engineer')),
                ('Copy_of_Tax', models.ImageField(upload_to='map_approval')),
                ('other_details', models.TextField(default='')),
                ('map_approved', models.ImageField(default='', upload_to='aproved_map')),
            ],
            options={
                'db_table': 'mapapproval',
            },
        ),
    ]
