# Generated by Django 2.1.1 on 2020-06-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0020_mapapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mapapproval',
        ),
    ]
