# Generated by Django 2.1.1 on 2020-06-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0023_loandetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loandetails',
        ),
    ]
