# Generated by Django 2.1.1 on 2020-06-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0025_loandetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandetails',
            name='date',
        ),
    ]
