# Generated by Django 2.1.1 on 2020-06-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0026_remove_loandetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
