# Generated by Django 2.1.1 on 2020-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0027_loandetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandetails',
            name='date',
        ),
        migrations.AddField(
            model_name='loandetails',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
