# Generated by Django 2.1.1 on 2020-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0028_auto_20200624_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapapproval',
            name='Copy_of_Tax',
            field=models.FileField(upload_to='map_approval/'),
        ),
        migrations.AlterField(
            model_name='mapapproval',
            name='Land_Paper',
            field=models.FileField(upload_to='map_approval/'),
        ),
    ]
