# Generated by Django 2.1.1 on 2020-06-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0029_auto_20200625_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loandetails',
        ),
        migrations.DeleteModel(
            name='mapapproval',
        ),
    ]
