# Generated by Django 2.1.1 on 2020-06-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0030_auto_20200625_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loandetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('loan_id', models.CharField(max_length=100)),
                ('Loan_Type', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Email_ID', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=100)),
                ('employee', models.CharField(max_length=100)),
                ('Income', models.CharField(max_length=100)),
                ('Loan_Required', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Loandetails',
            },
        ),
        migrations.CreateModel(
            name='mapapproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('Property_ID', models.CharField(max_length=100)),
                ('Buyer_ID', models.CharField(max_length=100)),
                ('Land_Paper', models.FileField(upload_to='map_approval/')),
                ('Map_by_engineer', models.ImageField(upload_to='map_by_engineer/')),
                ('Copy_of_Tax', models.FileField(upload_to='map_approval/')),
                ('other_details', models.TextField(default='')),
                ('map_approved', models.ImageField(default='', upload_to='aproved_map/')),
            ],
            options={
                'db_table': 'mapapproval',
            },
        ),
    ]
