# Generated by Django 2.1.1 on 2020-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0031_loandetails_mapapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='banner/')),
            ],
            options={
                'db_table': 'bannerimage',
            },
        ),
    ]
