# Generated by Django 2.1.1 on 2020-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0032_bannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(default='', upload_to='bannerimg/'),
        ),
    ]
