# Generated by Django 2.1.1 on 2020-07-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0037_auto_20200706_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foroffer',
            name='image',
        ),
    ]
