# Generated by Django 2.1.1 on 2020-07-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0038_remove_foroffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='offer',
            field=models.ImageField(default='', upload_to='offer/'),
        ),
    ]
