# Generated by Django 2.1.1 on 2020-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0039_bannerimage_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foroffer',
            name='Email_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='foroffer',
            table='foroffer',
        ),
    ]
