# Generated by Django 2.1.1 on 2020-07-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0040_auto_20200706_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foroffer',
        ),
    ]
