# Generated by Django 2.1.1 on 2020-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0041_delete_foroffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='foroffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('Email_ID', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'foroffer',
            },
        ),
    ]
