# Generated by Django 2.1.1 on 2020-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0042_foroffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foroffer',
            name='date',
        ),
        migrations.AddField(
            model_name='foroffer',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
