# Generated by Django 2.1.1 on 2020-07-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0044_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimagesdata',
            name='property_video',
            field=models.FileField(blank=True, null=True, upload_to='property_video/'),
        ),
    ]
