# Generated by Django 2.1.1 on 2020-07-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0045_propertyimagesdata_property_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimagesdata',
            name='property_video',
            field=models.FileField(blank=True, default='', upload_to='property_video/'),
        ),
    ]
