# Generated by Django 2.1.1 on 2020-07-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0046_auto_20200711_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_ID', models.CharField(max_length=100)),
                ('property_video', models.FileField(blank=True, default='', upload_to='property_video/')),
            ],
            options={
                'db_table': 'PropertyVideo',
            },
        ),
        migrations.RemoveField(
            model_name='propertyimagesdata',
            name='property_video',
        ),
    ]
