# Generated by Django 2.1.1 on 2020-07-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0047_auto_20200711_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvideo',
            name='Video_image',
            field=models.ImageField(blank=True, default='', upload_to='video_pic/'),
        ),
    ]
