# Generated by Django 2.1.1 on 2020-07-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0048_propertyvideo_video_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog_table',
            table=None,
        ),
    ]
