# Generated by Django 2.1.1 on 2020-07-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0049_auto_20200713_1216'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent_account',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cartdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='foroffer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='loandetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mapapproval',
            table=None,
        ),
        migrations.AlterModelTable(
            name='myaccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='propertycategorydata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='propertydata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='propertyimagesdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='propertyvideo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user_account',
            table=None,
        ),
    ]
