# Generated by Django 2.1.1 on 2020-07-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0050_auto_20200713_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandetails',
            name='date',
        ),
    ]
