# Generated by Django 2.1.1 on 2020-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0052_delete_loandetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loandetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('loan_id', models.CharField(max_length=100)),
                ('Loan_Type', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Email_ID', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=100)),
                ('employee', models.CharField(max_length=100)),
                ('Income', models.CharField(max_length=100)),
                ('Loan_Required', models.CharField(max_length=100)),
            ],
        ),
    ]
