# Generated by Django 2.1.1 on 2020-07-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0054_auto_20200714_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
