# Generated by Django 2.1.1 on 2020-07-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0055_auto_20200714_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loandetails',
        ),
    ]
