# Generated by Django 2.1.1 on 2020-07-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0058_admind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admind',
        ),
    ]
