# Generated by Django 2.1.1 on 2020-07-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0060_admind'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=100)),
                ('accountholdername', models.CharField(max_length=100)),
                ('checkpic', models.ImageField(upload_to='checkbookpics/')),
                ('bankname', models.CharField(max_length=100)),
                ('accountno', models.CharField(max_length=100)),
                ('IFSC', models.CharField(max_length=100)),
            ],
        ),
    ]
