# Generated by Django 2.1.1 on 2020-07-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0061_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='IFSC',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='accountholdername',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='accountno',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agent_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bankname',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='checkpic',
            field=models.ImageField(default='checkbookpics/WhatsApp_Image_2020-02-17_at_21.14.44.jpeg', upload_to='checkbookpics/'),
        ),
    ]
