# Generated by Django 2.1.1 on 2020-07-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0062_auto_20200718_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_account',
            name='Post',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
