# Generated by Django 2.1.1 on 2020-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0063_agent_account_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonialdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='testimonialimg/')),
                ('feedback', models.TextField(default='')),
            ],
        ),
    ]
