# Generated by Django 2.1.1 on 2020-07-21 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0064_testimonialdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_account',
            name='aadharcard',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='agentpic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent_account',
            name='agentpic',
            field=models.ImageField(blank=True, default='profilepic/image.png', upload_to='profilepic/'),
        ),
    ]
