# Generated by Django 2.1.1 on 2020-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0065_auto_20200721_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_account',
            name='aadharcard',
        ),
        migrations.AddField(
            model_name='agent_account',
            name='agentpic_is_aadharcard',
            field=models.ImageField(default='profilepic/image.png', upload_to='profileid/'),
        ),
        migrations.AlterField(
            model_name='agent_account',
            name='agentpic',
            field=models.ImageField(upload_to='agentpic'),
        ),
    ]
