# Generated by Django 2.1.1 on 2020-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0066_auto_20200721_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='Property_across',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='Property_Area',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
