# Generated by Django 2.1.1 on 2020-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0067_auto_20200721_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='admind',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='Property_across',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
